### ISSUE TITLE
Don't show flipper filters on player page

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1002]
![Image](https://user-images.githubusercontent.com/16632490/207395893-dc3e981a-2654-412d-88a8-05f0fa1bafe2.png)

There is no profit on bids thus the backend returns an error.  
That and the other flip filters should not be shown on the player page

**Comment by matthias-luger** [comment]
@Ekwav 
How should the frontend know what not to show?
I would prefer something like
1. Have the endpoint take a additional parameter like "type=bids", for it to only return certain filters
2. Have a seperate endpoint
3. Just return nothing / I just show nothing => bad user experience

Otherwise I would just hard code the filters to hide. If your ok with that, please give me a list of all the filters to hide

**Comment by Ekwav** [comment]
Simple,
Don't include the filters returned by the `flipFilters` command on things that aren't flips.
Only use the filters from the API to filter via the API.
