### ISSUE TITLE
Dots missing

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#1248]
Every big number input should have thousand separators.

![Image](https://github.com/Coflnet/hypixel-react/assets/16632490/841b0591-6610-4339-a202-bfb70857a17e)

https://discord.com/channels/267680588666896385/1231163182790344734/1231163250352328714

**Comment by matthias-luger** [comment]
@Ekwav This happens because MinProfit has the FilterType "Range" (does that even make sense?).
The Range filter support different custom inputs (like "1-100", ">20", "3k") and therefore the NumericInputs I use for the number inputs don't work with them.

![grafik](https://github.com/Coflnet/hypixel-react/assets/58751503/d964d3b8-5ac8-4948-af23-7cc25becd58f)
