### ISSUE TITLE
Add click event to profitable crafts

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#582]
There should be more information about a craft when it is clicked.
Some things requested so far
* lowest bin of ingredients
* lowest bin of the resulting item
* crafting recipe

**Comment by Ekwav** [comment]
I suggest showing a crafting table where clicking each item will navigate to the relevant item page

**Comment by matthias-luger** [comment]
@Ekwav what does the "selling price" currently represent? The lbin, right? Can I get the median as well, so I can display it there without the need of a navigation.

The crafting table: Should the crafting ingredients also get a crafting table and a link? If yes, I have to rework the hover-thing because you currently cant click the items in the popover. If not: Where exactly should I navigate to? The wiki page? Or "our" item page?

=> please describe the desired implementation in more detail

**Comment by Ekwav** [comment]
you can retrieve the recipe from here: https://sky.coflnet.com/api/craft/recipe/ASPECT_OF_THE_END 
note that recipes use the format of NEU so may contain a count.

On click a crafting table should become visible showing the recipe.
On click on either the ingredients or the result the /item page should be opened in a new tab
