### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by glaicodes** [matthias-luger/hypixel-react#691]
I have 2 suggestions.
1) Make these blurs really blur the item names. I can easily read the crafts, them being warden helmet, soulflow supercell and tier boost.![image](https://user-images.githubusercontent.com/75806392/154848349-d318b5c8-2211-4e10-a0a4-308673f96ec7.png)

2) This isn't true anymore.
![image](https://user-images.githubusercontent.com/75806392/154848293-a480ac32-5bed-4f09-a62b-46c8d9d09cab.png)

**Comment by matthias-luger** [comment]
1. This is known and on purpose. We never planed to enforce the first three crafts and there are multiple easy ways around them  (change the sorting, inspect element and remove blur, ...). It looks cool and should serve as a small incentive to buy premium.
2. Why is this not true anymore? You get 1 hour for invites and 20% of the premium time the invited person purchased

**Comment by glaicodes** [comment]
1. Im fine with that answer.

2. It doesn't say that in https://sky.coflnet.com/referral.
![image](https://user-images.githubusercontent.com/75806392/155536101-ce8fb5b8-2a69-42e5-a441-01ba9e51e4d1.png)

**Comment by matthias-luger** [comment]
It still says "If the invited person buys premium, you get 20% of the purchased premium time.".
Therefore the statement still holds true.
The 1 hour invite was removed, because it was abused and we initially wanted to remove it. In the end we decided against it, but removed any advertismement for the 1h, so people who get invited still get 1h to test it, but the abuse-rate is lowered. 
From our point of view, this seems to work quite will until now.

Also: We are currently implementing a new payment-system, which will renew a lot of things (https://github.com/Coflnet/hypixel-react/pull/631)

**Comment by matthias-luger** [comment]
It still says "If the invited person buys premium, you get 20% of the purchased premium time.".
Therefore the statement still holds true.
The 1 hour invite was removed, because it was abused and we initially wanted to remove it. In the end we decided against it, but removed any advertismement for the 1h, so people who get invited still get 1h to test it, but the abuse-rate is lowered. 
From our point of view, this seems to work quite will until now.

Also: We are currently implementing a new payment-system, which will renew a lot of things (https://github.com/Coflnet/hypixel-react/pull/631)

**Comment by matthias-luger** [comment]
It still says "If the invited person buys premium, you get 20% of the purchased premium time.".
Therefore the statement still holds true.
The 1 hour invite was removed, because it was abused and we initially wanted to remove it. In the end we decided against it, but removed any advertismement for the 1h, so people who get invited still get 1h to test it, but the abuse-rate is lowered. 
From our point of view, this seems to work quite will until now.

Also: We are currently implementing a new payment-system, which will renew a lot of things (https://github.com/Coflnet/hypixel-react/pull/631)
