### ISSUE TITLE
Bids don't refresh when navigating 

### ISSUE THREAD

**Issue by Ekwav** [matthias-luger/hypixel-react#864]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/16632490/178114333-aa43cc51-47a1-419e-bb68-3c1c52ff95aa.png">
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/16632490/178114354-321dc3a4-2ba3-4084-b02c-f54a6d8761ff.png">

**Comment by Ekwav** [comment]
I used the search to switch between the players.
Same issue for auctions

**Comment by Ekwav** [comment]
the auctions also don't refresh for me.  
AND another report claimed wildly different tracked flips results

**Comment by ThomasWu931** [comment]
I took a look at some of the files and I think the error  is caused because `PlayerDetailsList` doesn't unmount and remount when searching a new player. 

Since the `detailType` doesn't immediately change when swapping between players, `PlayerDetailsList` doesn't unmount, remount, and allow for `useState` to reinitialize the data. (https://github.com/Coflnet/hypixel-react/blob/develop/pages/player/%5Buuid%5D/index.tsx#L169-L176)

**Comment by Flou21** [comment]
the issue was reported again by one of our users
please try to merge a fix asap
